// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'6d17391f3570ac6893deff51f875e46473bec5efaa685fe102c24138a61e9411'>;
export type ExecutionHash =
  ExecutionHashBase<'f023a5b8bc56d974c465755ca54d12f2a30a9f5e7262d2dddff55e71bbbacc27'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Agendamento: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly medicoId: CodecTypes['pg/int4@1']['output'];
      readonly pacienteId: CodecTypes['pg/int4@1']['output'];
      readonly data: CodecTypes['pg/date-string@1']['output'];
      readonly horaInicio: CodecTypes['pg/text@1']['output'];
      readonly horaFim: CodecTypes['pg/text@1']['output'];
      readonly status:
        'AGENDADA' | 'PENDENTE' | 'CONFIRMADA' | 'REALIZADA' | 'RECUSADA' | 'CANCELADA' | 'FALTOU';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly CodigoPrimeiroAcesso: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly usuarioId: CodecTypes['pg/int4@1']['output'];
      readonly codigoHash: CodecTypes['pg/text@1']['output'];
      readonly expiraEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly usado: CodecTypes['pg/bool@1']['output'];
      readonly tentativas: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly CodigoRedefinicaoSenha: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly usuarioId: CodecTypes['pg/int4@1']['output'];
      readonly codigo: CodecTypes['pg/text@1']['output'];
      readonly expiraEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly usado: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly DisponibilidadeAgenda: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly medicoId: CodecTypes['pg/int4@1']['output'];
      readonly data: CodecTypes['pg/date-string@1']['output'];
      readonly horaInicio: CodecTypes['pg/text@1']['output'];
      readonly horaFim: CodecTypes['pg/text@1']['output'];
      readonly duracaoConsulta: CodecTypes['pg/int4@1']['output'];
      readonly ativo: CodecTypes['pg/bool@1']['output'];
    };
    readonly Medico: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly usuarioId: CodecTypes['pg/int4@1']['output'];
      readonly crm: CodecTypes['pg/text@1']['output'];
    };
    readonly Paciente: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly medicoId: CodecTypes['pg/int4@1']['output'];
      readonly usuarioId: CodecTypes['pg/int4@1']['output'] | null;
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly telefone: CodecTypes['pg/text@1']['output'] | null;
      readonly cpf: CodecTypes['pg/text@1']['output'] | null;
      readonly acessoLiberado: CodecTypes['pg/bool@1']['output'];
      readonly ativo: CodecTypes['pg/bool@1']['output'];
    };
    readonly RemarcacaoAgendamento: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly agendamentoId: CodecTypes['pg/int4@1']['output'];
      readonly novaData: CodecTypes['pg/date-string@1']['output'];
      readonly novaHoraInicio: CodecTypes['pg/text@1']['output'];
      readonly novaHoraFim: CodecTypes['pg/text@1']['output'];
      readonly status: 'PENDENTE' | 'ACEITA' | 'RECUSADA';
      readonly visualizadoPaciente: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Usuario: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly senha: CodecTypes['pg/text@1']['output'] | null;
      readonly tipo: 'ADMIN' | 'MEDICO' | 'PACIENTE';
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly primeiroAcesso: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Agendamento: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly medicoId: CodecTypes['pg/int4@1']['input'];
      readonly pacienteId: CodecTypes['pg/int4@1']['input'];
      readonly data: CodecTypes['pg/date-string@1']['input'];
      readonly horaInicio: CodecTypes['pg/text@1']['input'];
      readonly horaFim: CodecTypes['pg/text@1']['input'];
      readonly status:
        'AGENDADA' | 'PENDENTE' | 'CONFIRMADA' | 'REALIZADA' | 'RECUSADA' | 'CANCELADA' | 'FALTOU';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly CodigoPrimeiroAcesso: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly usuarioId: CodecTypes['pg/int4@1']['input'];
      readonly codigoHash: CodecTypes['pg/text@1']['input'];
      readonly expiraEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly usado: CodecTypes['pg/bool@1']['input'];
      readonly tentativas: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly CodigoRedefinicaoSenha: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly usuarioId: CodecTypes['pg/int4@1']['input'];
      readonly codigo: CodecTypes['pg/text@1']['input'];
      readonly expiraEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly usado: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly DisponibilidadeAgenda: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly medicoId: CodecTypes['pg/int4@1']['input'];
      readonly data: CodecTypes['pg/date-string@1']['input'];
      readonly horaInicio: CodecTypes['pg/text@1']['input'];
      readonly horaFim: CodecTypes['pg/text@1']['input'];
      readonly duracaoConsulta: CodecTypes['pg/int4@1']['input'];
      readonly ativo: CodecTypes['pg/bool@1']['input'];
    };
    readonly Medico: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly usuarioId: CodecTypes['pg/int4@1']['input'];
      readonly crm: CodecTypes['pg/text@1']['input'];
    };
    readonly Paciente: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly medicoId: CodecTypes['pg/int4@1']['input'];
      readonly usuarioId: CodecTypes['pg/int4@1']['input'] | null;
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly telefone: CodecTypes['pg/text@1']['input'] | null;
      readonly cpf: CodecTypes['pg/text@1']['input'] | null;
      readonly acessoLiberado: CodecTypes['pg/bool@1']['input'];
      readonly ativo: CodecTypes['pg/bool@1']['input'];
    };
    readonly RemarcacaoAgendamento: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly agendamentoId: CodecTypes['pg/int4@1']['input'];
      readonly novaData: CodecTypes['pg/date-string@1']['input'];
      readonly novaHoraInicio: CodecTypes['pg/text@1']['input'];
      readonly novaHoraFim: CodecTypes['pg/text@1']['input'];
      readonly status: 'PENDENTE' | 'ACEITA' | 'RECUSADA';
      readonly visualizadoPaciente: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Usuario: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly senha: CodecTypes['pg/text@1']['input'] | null;
      readonly tipo: 'ADMIN' | 'MEDICO' | 'PACIENTE';
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly primeiroAcesso: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly agendamento: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly data: CodecTypes['pg/date-string@1']['output'];
      readonly horaFim: CodecTypes['pg/text@1']['output'];
      readonly horaInicio: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly medicoId: CodecTypes['pg/int4@1']['output'];
      readonly pacienteId: CodecTypes['pg/int4@1']['output'];
      readonly status:
        'AGENDADA' | 'PENDENTE' | 'CONFIRMADA' | 'REALIZADA' | 'RECUSADA' | 'CANCELADA' | 'FALTOU';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly codigoPrimeiroAcesso: {
      readonly codigoHash: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly expiraEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly tentativas: CodecTypes['pg/int4@1']['output'];
      readonly usado: CodecTypes['pg/bool@1']['output'];
      readonly usuarioId: CodecTypes['pg/int4@1']['output'];
    };
    readonly codigoRedefinicaoSenha: {
      readonly codigo: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly expiraEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly usado: CodecTypes['pg/bool@1']['output'];
      readonly usuarioId: CodecTypes['pg/int4@1']['output'];
    };
    readonly disponibilidadeAgenda: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly data: CodecTypes['pg/date-string@1']['output'];
      readonly duracaoConsulta: CodecTypes['pg/int4@1']['output'];
      readonly horaFim: CodecTypes['pg/text@1']['output'];
      readonly horaInicio: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly medicoId: CodecTypes['pg/int4@1']['output'];
    };
    readonly medico: {
      readonly crm: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly usuarioId: CodecTypes['pg/int4@1']['output'];
    };
    readonly paciente: {
      readonly acessoLiberado: CodecTypes['pg/bool@1']['output'];
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly cpf: CodecTypes['pg/text@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly medicoId: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly telefone: CodecTypes['pg/text@1']['output'] | null;
      readonly usuarioId: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly remarcacaoAgendamento: {
      readonly agendamentoId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly novaData: CodecTypes['pg/date-string@1']['output'];
      readonly novaHoraFim: CodecTypes['pg/text@1']['output'];
      readonly novaHoraInicio: CodecTypes['pg/text@1']['output'];
      readonly status: 'PENDENTE' | 'ACEITA' | 'RECUSADA';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly visualizadoPaciente: CodecTypes['pg/bool@1']['output'];
    };
    readonly usuario: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly primeiroAcesso: CodecTypes['pg/bool@1']['output'];
      readonly senha: CodecTypes['pg/text@1']['output'] | null;
      readonly tipo: 'ADMIN' | 'MEDICO' | 'PACIENTE';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly agendamento: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly data: CodecTypes['pg/date-string@1']['input'];
      readonly horaFim: CodecTypes['pg/text@1']['input'];
      readonly horaInicio: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly medicoId: CodecTypes['pg/int4@1']['input'];
      readonly pacienteId: CodecTypes['pg/int4@1']['input'];
      readonly status:
        'AGENDADA' | 'PENDENTE' | 'CONFIRMADA' | 'REALIZADA' | 'RECUSADA' | 'CANCELADA' | 'FALTOU';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly codigoPrimeiroAcesso: {
      readonly codigoHash: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly expiraEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly tentativas: CodecTypes['pg/int4@1']['input'];
      readonly usado: CodecTypes['pg/bool@1']['input'];
      readonly usuarioId: CodecTypes['pg/int4@1']['input'];
    };
    readonly codigoRedefinicaoSenha: {
      readonly codigo: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly expiraEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly usado: CodecTypes['pg/bool@1']['input'];
      readonly usuarioId: CodecTypes['pg/int4@1']['input'];
    };
    readonly disponibilidadeAgenda: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly data: CodecTypes['pg/date-string@1']['input'];
      readonly duracaoConsulta: CodecTypes['pg/int4@1']['input'];
      readonly horaFim: CodecTypes['pg/text@1']['input'];
      readonly horaInicio: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly medicoId: CodecTypes['pg/int4@1']['input'];
    };
    readonly medico: {
      readonly crm: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly usuarioId: CodecTypes['pg/int4@1']['input'];
    };
    readonly paciente: {
      readonly acessoLiberado: CodecTypes['pg/bool@1']['input'];
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly cpf: CodecTypes['pg/text@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly medicoId: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly telefone: CodecTypes['pg/text@1']['input'] | null;
      readonly usuarioId: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly remarcacaoAgendamento: {
      readonly agendamentoId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly novaData: CodecTypes['pg/date-string@1']['input'];
      readonly novaHoraFim: CodecTypes['pg/text@1']['input'];
      readonly novaHoraInicio: CodecTypes['pg/text@1']['input'];
      readonly status: 'PENDENTE' | 'ACEITA' | 'RECUSADA';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly visualizadoPaciente: CodecTypes['pg/bool@1']['input'];
    };
    readonly usuario: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly primeiroAcesso: CodecTypes['pg/bool@1']['input'];
      readonly senha: CodecTypes['pg/text@1']['input'] | null;
      readonly tipo: 'ADMIN' | 'MEDICO' | 'PACIENTE';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly agendamento: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly medicoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly pacienteId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly data: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly horaInicio: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly horaFim: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDENTE'>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'agendamento_medicoId_data_idx_20edd9d1';
                  readonly prefix: 'agendamento_medicoId_data_idx';
                  readonly columns: readonly ['medicoId', 'data'];
                  readonly unique: false;
                },
                {
                  readonly name: 'agendamento_pacienteId_data_idx_4b9c5eee';
                  readonly prefix: 'agendamento_pacienteId_data_idx';
                  readonly columns: readonly ['pacienteId', 'data'];
                  readonly unique: false;
                },
                {
                  readonly name: 'agendamento_medicoId_data_horaInicio_idx_1b9f7301';
                  readonly prefix: 'agendamento_medicoId_data_horaInicio_idx';
                  readonly columns: readonly ['medicoId', 'data', 'horaInicio'];
                  readonly unique: false;
                },
                {
                  readonly name: 'agendamento_medicoId_idx_cef7d96a';
                  readonly prefix: 'agendamento_medicoId_idx';
                  readonly columns: readonly ['medicoId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'agendamento_pacienteId_idx_8734dc3f';
                  readonly prefix: 'agendamento_pacienteId_idx';
                  readonly columns: readonly ['pacienteId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agendamento';
                    readonly columns: readonly ['medicoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'medico';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agendamento';
                    readonly columns: readonly ['pacienteId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'paciente';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly codigoPrimeiroAcesso: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly usuarioId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly codigoHash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly expiraEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly usado: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly tentativas: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'codigoPrimeiroAcesso_usuarioId_idx_5f01c7d6';
                  readonly prefix: 'codigoPrimeiroAcesso_usuarioId_idx';
                  readonly columns: readonly ['usuarioId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'codigoPrimeiroAcesso_usuarioId_usado_idx_564cb520';
                  readonly prefix: 'codigoPrimeiroAcesso_usuarioId_usado_idx';
                  readonly columns: readonly ['usuarioId', 'usado'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'codigoPrimeiroAcesso';
                    readonly columns: readonly ['usuarioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly codigoRedefinicaoSenha: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly usuarioId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly codigo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly expiraEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly usado: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'codigoRedefinicaoSenha_usuarioId_idx_5f01c7d6';
                  readonly prefix: 'codigoRedefinicaoSenha_usuarioId_idx';
                  readonly columns: readonly ['usuarioId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'codigoRedefinicaoSenha';
                    readonly columns: readonly ['usuarioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly disponibilidadeAgenda: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly medicoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly data: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly horaInicio: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly horaFim: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly duracaoConsulta: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 30>;
                  };
                };
                readonly ativo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'disponibilidadeAgenda_medicoId_data_idx_20edd9d1';
                  readonly prefix: 'disponibilidadeAgenda_medicoId_data_idx';
                  readonly columns: readonly ['medicoId', 'data'];
                  readonly unique: false;
                },
                {
                  readonly name: 'disponibilidadeAgenda_medicoId_idx_cef7d96a';
                  readonly prefix: 'disponibilidadeAgenda_medicoId_idx';
                  readonly columns: readonly ['medicoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'disponibilidadeAgenda';
                    readonly columns: readonly ['medicoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'medico';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly medico: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly usuarioId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly crm: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['usuarioId'] },
                { readonly columns: readonly ['crm'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'medico';
                    readonly columns: readonly ['usuarioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly paciente: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly medicoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly usuarioId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly telefone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly cpf: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly acessoLiberado: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly ativo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['usuarioId'] },
                { readonly columns: readonly ['cpf'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'paciente_medicoId_idx_cef7d96a';
                  readonly prefix: 'paciente_medicoId_idx';
                  readonly columns: readonly ['medicoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'paciente';
                    readonly columns: readonly ['medicoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'medico';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'paciente';
                    readonly columns: readonly ['usuarioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly remarcacaoAgendamento: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly agendamentoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly novaData: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly novaHoraInicio: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly novaHoraFim: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDENTE'>;
                  };
                };
                readonly visualizadoPaciente: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'remarcacaoAgendamento_agendamentoId_idx_b943086d';
                  readonly prefix: 'remarcacaoAgendamento_agendamentoId_idx';
                  readonly columns: readonly ['agendamentoId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'remarcacaoAgendamento_status_idx_e98638ab';
                  readonly prefix: 'remarcacaoAgendamento_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'remarcacaoAgendamento';
                    readonly columns: readonly ['agendamentoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agendamento';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly usuario: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly senha: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly tipo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly ativo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly primeiroAcesso: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly StatusAgendamento: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'AGENDADA',
                'PENDENTE',
                'CONFIRMADA',
                'REALIZADA',
                'RECUSADA',
                'CANCELADA',
                'FALTOU',
              ];
            };
            readonly StatusRemarcacao: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDENTE', 'ACEITA', 'RECUSADA'];
            };
            readonly TipoUsuario: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ADMIN', 'MEDICO', 'PACIENTE'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly usuario: { readonly namespace: 'public' & NamespaceId; readonly model: 'Usuario' };
    readonly medico: { readonly namespace: 'public' & NamespaceId; readonly model: 'Medico' };
    readonly paciente: { readonly namespace: 'public' & NamespaceId; readonly model: 'Paciente' };
    readonly disponibilidadeAgenda: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'DisponibilidadeAgenda';
    };
    readonly agendamento: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Agendamento';
    };
    readonly remarcacaoAgendamento: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RemarcacaoAgendamento';
    };
    readonly codigoRedefinicaoSenha: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'CodigoRedefinicaoSenha';
    };
    readonly codigoPrimeiroAcesso: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'CodigoPrimeiroAcesso';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Agendamento: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly medicoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly pacienteId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly data: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly horaInicio: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly horaFim: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly medico: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Medico';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['medicoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly paciente: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Paciente';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['pacienteId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly remarcacoes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RemarcacaoAgendamento';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['agendamentoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'agendamento';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly medicoId: { readonly column: 'medicoId' };
                readonly pacienteId: { readonly column: 'pacienteId' };
                readonly data: { readonly column: 'data' };
                readonly horaInicio: { readonly column: 'horaInicio' };
                readonly horaFim: { readonly column: 'horaFim' };
                readonly status: { readonly column: 'status' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly CodigoPrimeiroAcesso: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly usuarioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly codigoHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly expiraEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly usado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly tentativas: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly usuario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['usuarioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'codigoPrimeiroAcesso';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly usuarioId: { readonly column: 'usuarioId' };
                readonly codigoHash: { readonly column: 'codigoHash' };
                readonly expiraEm: { readonly column: 'expiraEm' };
                readonly usado: { readonly column: 'usado' };
                readonly tentativas: { readonly column: 'tentativas' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly CodigoRedefinicaoSenha: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly usuarioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly codigo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly expiraEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly usado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly usuario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['usuarioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'codigoRedefinicaoSenha';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly usuarioId: { readonly column: 'usuarioId' };
                readonly codigo: { readonly column: 'codigo' };
                readonly expiraEm: { readonly column: 'expiraEm' };
                readonly usado: { readonly column: 'usado' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly DisponibilidadeAgenda: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly medicoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly data: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly horaInicio: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly horaFim: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly duracaoConsulta: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly ativo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly medico: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Medico';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['medicoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'disponibilidadeAgenda';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly medicoId: { readonly column: 'medicoId' };
                readonly data: { readonly column: 'data' };
                readonly horaInicio: { readonly column: 'horaInicio' };
                readonly horaFim: { readonly column: 'horaFim' };
                readonly duracaoConsulta: { readonly column: 'duracaoConsulta' };
                readonly ativo: { readonly column: 'ativo' };
              };
            };
          };
          readonly Medico: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly usuarioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly crm: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly agendamentos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Agendamento';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['medicoId'];
                };
              };
              readonly disponibilidades: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DisponibilidadeAgenda';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['medicoId'];
                };
              };
              readonly pacientes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Paciente';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['medicoId'];
                };
              };
              readonly usuario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['usuarioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'medico';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly usuarioId: { readonly column: 'usuarioId' };
                readonly crm: { readonly column: 'crm' };
              };
            };
          };
          readonly Paciente: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly medicoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly usuarioId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly telefone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly cpf: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly acessoLiberado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly ativo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly agendamentos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Agendamento';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['pacienteId'];
                };
              };
              readonly medico: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Medico';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['medicoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly usuario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['usuarioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'paciente';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly medicoId: { readonly column: 'medicoId' };
                readonly usuarioId: { readonly column: 'usuarioId' };
                readonly nome: { readonly column: 'nome' };
                readonly email: { readonly column: 'email' };
                readonly telefone: { readonly column: 'telefone' };
                readonly cpf: { readonly column: 'cpf' };
                readonly acessoLiberado: { readonly column: 'acessoLiberado' };
                readonly ativo: { readonly column: 'ativo' };
              };
            };
          };
          readonly RemarcacaoAgendamento: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly agendamentoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly novaData: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly novaHoraInicio: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly novaHoraFim: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly visualizadoPaciente: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly agendamento: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Agendamento';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['agendamentoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'remarcacaoAgendamento';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly agendamentoId: { readonly column: 'agendamentoId' };
                readonly novaData: { readonly column: 'novaData' };
                readonly novaHoraInicio: { readonly column: 'novaHoraInicio' };
                readonly novaHoraFim: { readonly column: 'novaHoraFim' };
                readonly status: { readonly column: 'status' };
                readonly visualizadoPaciente: { readonly column: 'visualizadoPaciente' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Usuario: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly senha: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tipo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ativo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly primeiroAcesso: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly codigosPrimeiroAcesso: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'CodigoPrimeiroAcesso';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['usuarioId'];
                };
              };
              readonly codigosRedefinicao: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'CodigoRedefinicaoSenha';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['usuarioId'];
                };
              };
              readonly medico: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Medico';
                };
                readonly cardinality: '1:1';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['usuarioId'];
                };
              };
              readonly paciente: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Paciente';
                };
                readonly cardinality: '1:1';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['usuarioId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'usuario';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly email: { readonly column: 'email' };
                readonly senha: { readonly column: 'senha' };
                readonly tipo: { readonly column: 'tipo' };
                readonly ativo: { readonly column: 'ativo' };
                readonly primeiroAcesso: { readonly column: 'primeiroAcesso' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly TipoUsuario: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ADMIN'; readonly value: 'ADMIN' },
              { readonly name: 'MEDICO'; readonly value: 'MEDICO' },
              { readonly name: 'PACIENTE'; readonly value: 'PACIENTE' },
            ];
          };
          readonly StatusAgendamento: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'AGENDADA'; readonly value: 'AGENDADA' },
              { readonly name: 'PENDENTE'; readonly value: 'PENDENTE' },
              { readonly name: 'CONFIRMADA'; readonly value: 'CONFIRMADA' },
              { readonly name: 'REALIZADA'; readonly value: 'REALIZADA' },
              { readonly name: 'RECUSADA'; readonly value: 'RECUSADA' },
              { readonly name: 'CANCELADA'; readonly value: 'CANCELADA' },
              { readonly name: 'FALTOU'; readonly value: 'FALTOU' },
            ];
          };
          readonly StatusRemarcacao: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDENTE'; readonly value: 'PENDENTE' },
              { readonly name: 'ACEITA'; readonly value: 'ACEITA' },
              { readonly name: 'RECUSADA'; readonly value: 'RECUSADA' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'agendamento';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'remarcacaoAgendamento';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'usuario';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
